// Auto-generated by mmk-cn — edit CARD_DURATIONS after TTS
export const FPS = 30;

export const CARD_COUNT = 3;
export const CARD_WIDTH = 1080;
export const CARD_HEIGHT = 1350;
export const VERTICAL_WIDTH = 1080;
export const VERTICAL_HEIGHT = 1920;

// Default: 5 seconds per card (150 frames). Replace with TTS timings.
const ACTUAL_CARD_FRAMES = [150, 150, 150];
export const TOTAL_FRAMES = ACTUAL_CARD_FRAMES.reduce((a, b) => a + b, 0);

export const CARD_DURATIONS = ACTUAL_CARD_FRAMES;

// Subtitle lines — populate after TTS script is written
export const SUBTITLE_LINES: string[][] = [
  [],
  [],
  [],
];

export type SubtitleSegment = {
  start: number;
  end: number;
  text: string;
};

const getTextWeight = (text: string): number => text.replace(/\s+/g, "").length;

const distributeByWeights = (total: number, weights: number[]): number[] => {
  const weightSum = weights.reduce((sum, w) => sum + w, 0);
  const raw = weights.map((w) => (w / weightSum) * total);
  const base = raw.map((v) => Math.floor(v));
  let remainder = total - base.reduce((s, v) => s + v, 0);
  const ranked = raw
    .map((v, i) => ({ index: i, fraction: v - Math.floor(v) }))
    .sort((a, b) => b.fraction - a.fraction);
  for (let i = 0; i < ranked.length && remainder > 0; i++) {
    base[ranked[i].index] += 1;
    remainder -= 1;
  }
  return base;
};

export const SUBTITLE_SEGMENTS: SubtitleSegment[] = (() => {
  const segments: SubtitleSegment[] = [];
  let cursor = 0;
  SUBTITLE_LINES.forEach((lines, cardIndex) => {
    if (lines.length === 0) {
      cursor += CARD_DURATIONS[cardIndex];
      return;
    }
    const framesPerLine = distributeByWeights(
      CARD_DURATIONS[cardIndex],
      lines.map(getTextWeight),
    );
    let localCursor = cursor;
    lines.forEach((text, lineIndex) => {
      segments.push({
        start: localCursor,
        end: localCursor + framesPerLine[lineIndex],
        text,
      });
      localCursor += framesPerLine[lineIndex];
    });
    cursor += CARD_DURATIONS[cardIndex];
  });
  return segments;
})();
